### ISSUE TITLE
Add plain TXT files for plot and names

### ISSUE THREAD

**Issue by yuleeque** [hadgehog/TeamZ#12]
Meanwhile, all the best ideas are stored here in comments.

**Comment by yuleeque** [comment]
Possible game names:
- Team Z
- Project Z
- Utmost Plan
- Utmost Team
- Utmost Defense Plan (UDP)
- Utmost Defense Forces ('cause "UDF" sounds nice)
- Defense Plan
- Defense Forces
- Invincible Team
- Unbeatable Team

**Comment by hadgehog** [comment]
done

**Comment by yuleeque** [comment]
53a1676
