### ISSUE TITLE
At Lvl1:Stg1 game won't let to transfer to Stg2, "E" button doesn't work

### ISSUE THREAD

**Issue by dmitryohai** [hadgehog/TeamZ#23]
Everything works fine till that hole on the wall. There, Main Character freezes, cannot move at all, plus "E" button doesn't transfer me to Stg2. Meanwhile, the 2nd Character is still fully operable, so game is active.
![lvl1 stg1](https://user-images.githubusercontent.com/44348938/58431075-d9ea7280-80b4-11e9-9cb2-fff4d8f6bc47.png)

**Comment by hadgehog** [comment]
Could not reproduce.

**Comment by byme8** [comment]
Zone to show message 'Press E to go inside' was bigger than door itself.

**Comment by hadgehog** [comment]
lol, stupid bug
