### ISSUE TITLE
Lvl1: Stg2 Main Character (Lizard) freezes after trying to get to the hole in the wall.

### ISSUE THREAD

**Issue by dmitryohai** [hadgehog/TeamZ#27]
Steps to reproduce:
1. After dealing with the gun, jump on the box near entrance and from this box jump to the grid above.
2. Left and above the grid there is a hole in the wall which (I suppose) must be a transition to the following stage. 
3. Move to this hole and press "E" (there is not hint to press it).
4. The Lizard falls down and freezes, you can no longer operate it. The rest of the game remains active, you can still operate the 2nd character. 
![lvl1 stg2 freeze](https://user-images.githubusercontent.com/44348938/58516611-3df26100-81b1-11e9-879a-1936119bff19.png)

**Comment by yuleeque** [comment]
Both are in jump state on 1st startup.
And returns to that state after performing a jump.
![image](https://user-images.githubusercontent.com/41265813/58625403-b735a500-82d2-11e9-98dc-75bf9bc2af02.png)

**Comment by byme8** [comment]
I can't reproduce. I guess it's fixed as part of #23
