### ISSUE TITLE
Won't move to the next Stage

### ISSUE THREAD

**Issue by yuleeque** [hadgehog/TeamZ#30]
**### After listening to main theme in main menu** I started the game moving both characters simultaneously. They experienced something (like stuck) at the top of the ladder but then moved to the ventilation. Then I've lost control on **WASD**. The **Left-Up-Right-Down** moves normally but ignores pressing "E" button to move to the next Stage.
Both of them were on grid right under the ventilation.

**Comment by hadgehog** [comment]
Give us a screenshot please

**Comment by yuleeque** [comment]
exactly that run. didn't close or restart
![image](https://user-images.githubusercontent.com/41265813/58629548-0bde1d80-82dd-11e9-9e37-90e9f09be4e9.png)

**Comment by yuleeque** [comment]
Makes me think that "E" button is attached to WASD character only.
Just a guess.

**Comment by byme8** [comment]
What version of app are you using? I guess this issue is fixed in #23, but you are using old build

**Comment by yuleeque** [comment]
It was v2019.05.26
Since I can't reproduce it too, let this Issue to be open for a while in case someone gets the same problem.
