### ISSUE TITLE
Hints still being displayed when back to Main menu 

### ISSUE THREAD

**Issue by yuleeque** [hadgehog/TeamZ#31]
(ESC when playing)

![image](https://user-images.githubusercontent.com/41265813/58703156-0ac5f280-83a8-11e9-806e-ccfbf842f1c6.png)
![image](https://user-images.githubusercontent.com/41265813/58703166-11ed0080-83a8-11e9-838b-d635fa120471.png)

**Comment by hadgehog** [comment]
заассайни на меня, плез, а то я с тела не могу

**Comment by hadgehog** [comment]
fixed
