### ISSUE TITLE
Charachers alighment on a grid

### ISSUE THREAD

**Issue by yuleeque** [hadgehog/TeamZ#39]
They aren't fixed and each time when trying to move upper or lower than the grid's border, they still make a small step followed by bringing them back to the border.

![image](https://user-images.githubusercontent.com/41265813/59147438-e6979080-89fb-11e9-9e08-f75e96a296d9.png)

**Comment by hadgehog** [comment]
и че?

**Comment by byme8** [comment]
it looks weird

**Comment by hadgehog** [comment]
not a bug

**Comment by yuleeque** [comment]
not a bug. just unfinished alignment system :)
