### ISSUE TITLE
Lab disappears on restart

### ISSUE THREAD

**Issue by yuleeque** [hadgehog/TeamZ#44]
On pressing "New Game" for a second time (and further).
This state remains when moving to the next level.

![image](https://user-images.githubusercontent.com/41265813/59566653-44168780-9063-11e9-9392-ad4cf65807d3.png)

![image](https://user-images.githubusercontent.com/41265813/59566736-69f05c00-9064-11e9-9eac-3abd69e30940.png)

**Comment by byme8** [comment]
Fixed in #43
