### ISSUE TITLE
Lizard slides during X and Z strikes on the run.

### ISSUE THREAD

**Issue by yuleeque** [hadgehog/TeamZ#7]
Possible fixes:
**a)** Redraw animation to include actions while running.
**b)** Make character stop when performing actions.

Ideally, **a)** for hands and **b)** for tail. 
Way more realistic and saves from drawing more complex tail-while-running animation.

**Comment by hadgehog** [comment]
Solution: new animation (running with hand punch) for hand punch and stopping running for leg kick and combo tail strike.

**Comment by yuleeque** [comment]
I doubt it depends on sprites. Seems it's all about the code.

Seems like "stand" position is ON right after each strike and would be better to use the previous state right after strikes, POSSIBLY:

` **Xing** -> strike -> always **X-ing** a few frames (small fraction of sec) -> Ying` 
where `X` is running or standing, `Y` is a different movement or the same

So it will look like they run, make strike and still moving a little (physically they are, but animation stucks)

**Comment by yuleeque** [comment]
**commentary**: not fixed due to no update released ->  repo moved to another SVN
